#!/usr/bin/env bash
# Bundle the multi-file Lua source tree at lua/scripts/ServerAuthority/
# into a single deployable script for Avledet's mod loader.
#
# Avledet's Lua sandbox excludes `require`, `dofile`, `loadfile`, and `load`
# (see library/src/API.cpp `safe_functions` whitelist). Each script directory
# in Avledet's data/lua/scripts/ has exactly ONE entry .lua file.
#
# Strategy: concatenate the support modules (each wrapped as IIFE returning
# their module table) followed by the entry script. The entry script
# references the IIFE locals as if they were require()'d.
#
# Usage:
#   ./tools/bundle.sh                    # writes dist/ServerAuthority.lua
#   ./tools/bundle.sh path/to/output.lua # custom output path

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/lua/scripts/ServerAuthority"
OUT="${1:-$ROOT/dist/ServerAuthority.lua}"

mkdir -p "$(dirname "$OUT")"

# Wrap a module file body as `local NAME = (function() <body> end)()`.
# Strips the file's trailing `return M` is not needed — we keep it; the IIFE
# evaluates to whatever the module returns.
wrap_module() {
    local local_name="$1"
    local module_path="$2"
    echo ""
    echo "-- ============================================================"
    echo "-- ===== Inlined from $(basename "$module_path") ====="
    echo "-- ============================================================"
    echo "local $local_name = (function()"
    cat "$module_path"
    echo "end)()"
}

{
    cat <<'HEADER'
--[[
    ServerAuthority bundled deploy artifact — DO NOT EDIT BY HAND.
    Generated by tools/bundle.sh from:
        lua/scripts/ServerAuthority/lib_vec.lua
        lua/scripts/ServerAuthority/mob_registry.lua
        lua/scripts/ServerAuthority/stub_ai.lua
        lua/scripts/ServerAuthority/ServerAuthority.lua  (entry)
    Source of truth: https://github.com/Sergentval/Avledet-ServerAuthority
--]]
HEADER

    wrap_module "lib_vec"      "$SRC/lib_vec.lua"
    wrap_module "mob_registry" "$SRC/mob_registry.lua"
    wrap_module "stub_ai"      "$SRC/stub_ai.lua"

    echo ""
    echo "-- ============================================================"
    echo "-- ===== Entry script (ServerAuthority.lua) ====="
    echo "-- ============================================================"
    cat "$SRC/ServerAuthority.lua"
} > "$OUT"

echo "Wrote: $OUT ($(wc -l < "$OUT") lines)"

# Optional Lua syntax check if a Lua compiler is available locally.
if command -v luac5.4 &>/dev/null; then
    if luac5.4 -p "$OUT"; then
        echo "Syntax check: OK (luac5.4)"
    else
        echo "Syntax check: FAILED" >&2
        exit 1
    fi
elif command -v luac &>/dev/null; then
    if luac -p "$OUT"; then
        echo "Syntax check: OK (luac)"
    else
        echo "Syntax check: FAILED" >&2
        exit 1
    fi
else
    echo "Syntax check: skipped (no luac in PATH; install lua5.4 to enable)"
fi
